# Generated by Django 3.2.12 on 2022-03-06 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_remove_cancion_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='link',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='place',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='position',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='rating',
        ),
        migrations.AddField(
            model_name='cancion',
            name='artist',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='peak',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='peak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='rank',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='weeks',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='weeks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancion',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
